services:
  database:
    image: postgres:15
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-narcissus}
      POSTGRES_PASSWORD: ${POSTGRES_USER:-narcissus}
      POSTGRES_DB: ${POSTGRES_USER:-narcissus}
