addSbtPlugin("org.scala-js"              % "sbt-scalajs"      % "1.13.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"     % "0.4.2")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"     % "0.11.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"     % "2.5.0")
addSbtPlugin("com.github.reibitto"       % "sbt-welcome"      % "0.3.1")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"    % "0.11.0")
addSbtPlugin("org.typelevel"             % "sbt-feral-lambda" % "0.2.2")
