#!/usr/bin/env bash
#

set -e

source ./scripts/nix-funcs.sh

function build_prod_frontend() {
  inDevShell yarn
  inDevShell sbt "narcissusApp/fullOptJS"
  inDevShell npm run build
}

build_prod_frontend
