#!/usr/bin/env bash

set -e

source ./scripts/nix-funcs.sh

function devShellTerraform {
        inDevShell terraform -chdir="./deployment" $@
}

function apply_tf {
        bucket="${TF_BACKEND_STATE_BUCKET:=narcissus-tf-state-staging-us-west-2}"
        inDevShell git-crypt unlock ./git-crypt-secret.key
        devShellTerraform init -backend-config="bucket=${bucket}" -migrate-state
        devShellTerraform plan \
            -var-file=./variables/variables.tfvars -out=tfplan
        devShellTerraform apply tfplan
}

apply_tf
