name: deploy

on:
  push:
    branches:
      - main
      - 'bugfix/**'
      - 'feature/js/add-tf-serverless-setup'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Install git-crypt the dumb way
        run: sudo apt-get update && sudo apt-get install -y git-crypt

      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-22.11
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v12
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: jisantuc

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}

      - name: Build production app
        run: ./scripts/build
        env:
          AUTH0_DOMAIN: ${{ vars.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ vars.AUTH0_CLIENT_ID }}

      - name: Save git-crypt key
        run: echo "${{ secrets.GIT_CRYPT_SECRET_KEY }}" | base64 --decode > git-crypt-secret.key

      - name: Deploy server
        run: nix develop -c bash ./scripts/infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy Frontend 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: dist

